module.exports.order = [
  "Head Accessory",
  "Glasses",
  "Mouth Accessory",
  "Hair",
  "Earlobe upper",
  "Earlobe Lower",
  "Orbital Piercing",
  "Industrial Piercing",
  "Helix Piercing",
  "Tragus Piercing",
  "Snug Piercing",
  "Hair Behind",
  "Neck Accessory",
  "Clothes",
  "Chest Accessory",
  "Eye Accessory",
  "Eyes",
  "Eyelashes + Liner",
  "Eye Shadow",
  "Eyebrows",
  "Nose Accessory",
  "Under Eye Makeup",
  "Face Paint",
  "Blush",
  "Cheekbone",
  "Nose Piercing Right",
  "Nose Piercing Left",
  "Septum Piercing",
  "Monroe Piercing",
  "Mesuda Piercing",
  "Madonna Piercing",
  "Labret Right",
  "Labret Left",
  "Labret Centre",
  "Lipstick",
  "Bridge Piercing",
  "Beauty Mark",
  "Forehead Tattoo",
  "Scalp Tattoo",
  "Head Side Tattoo",
  "Shoulder Tattoo",
  "Chest Tattoo",
  "Base",
  "Behind Eye Makeup",
  "Skin Tone",
  "Background",
];
