module.exports.roof = {
  "Head Accessory": 0.1,
  Glasses: 0.1,
  "Mouth Accessory": 0.1,
  "Earlobe upper": 0.25,
  "Earlobe Lower": 0.4,
  "Orbital Piercing": 0.1,
  "Industrial Piercing": 0.1,
  "Helix Piercing": 0.1,
  "Tragus Piercing": 1,
  "Snug Piercing": 0.1,
  "Neck Accessory": 0.2,
  Clothes: 0.25,
  "Chest Accessory": 0.1,
  "Eye Accessory": 0.05,
  Eyes: 0.1,
  "Eyelashes + Liner": 0.9,
  "Eye Shadow": 0.8,
  "Nose Accessory": 0.05,
  "Under Eye Makeup": 0.1,
  "Face Paint": 0.05,
  Blush: 0.4,
  Cheekbone: 0.25,
  "Nose Piercing Right": 0.1,
  "Nose Piercing Left": 0.1,
  "Septum Piercing": 0.1,
  "Monroe Piercing": 0.2,
  "Mesuda Piercing": 0.2,
  "Madonna Piercing": 0.2,
  "Labret Right Piercing": 0.2,
  "Labret Left Piercing": 0.2,
  "Labret Centre Piercing": 0.2,
  "Bridge Piercing": 0.3,
  "Beauty Mark": 0.1,
  "Forehead Tattoo": 0.2,
  "Scalp Tattoo": 0.1,
  "Head Side Tattoo": 0.2,
  "Shoulder Tattoo": 0.3,
  "Chest Tattoo": 0.2,
};
