module.exports.traits = {
  "Head Accessory": {
    "Bat ears": 0.1,
    "Black bunny ears": 0.2,
    "Black heart clip": 0.1,
    "Cat ear headband": 0.1,
    "Cat ears": 0.05,
    "Gold tiara": 0.001,
    "Hair clips": 0.2,
    "Halo": 0.01,
    "Heart headset": 0.1,
    "Hockey mask": 0.01,
    "Horns": 0.1,
    "Lilac bow": 0.2,
    "Lilac headphones": 0.2,
    "Lilac headset": 0.2,
    "Pink bunny ears": 0.2,
    "Pink headset": 0.2,
    "Red heart clip": 0.1,
    "Skull + ears": 0.05,
    "White bunny ears": 0.2
  },
  "Glasses": {
    "Two tone glasses": 0.05,
    "Thick rim black": 0.1,
    "Secretary glasses": 0.1,
    "Scouter": 0.01,
    "Pink sunglasses": 0.05,
    "Nerd glasses": 0.1,
    "Heart sunglasses": 0.1,
    "Gold rim glasses": 0.01,
    "Giant round glasses": 0.1,
    "Cool guy": 0.1,
    "Cat eye sunglasses": 0.1,
    "Cat eye black": 0.1
  },
  "Mouth Accessory": {
    "X mask": 0.05,
    "Pink vape": 0.05,
    "Pentagram mask": 0.05,
    "Lilac vape": 0.05,
    "Cross mask": 0.05,
    "Black vape": 0.05,
    "Tongue out": 0.05,
    "Demon teeth": 0.01
  },
  "Hair": {
    "Witch hat": 0.01,
    "Pink beanie": 0.2,
    "Pink cat cap": 0.2,
    "Pink baseball cap": 0.2,
    "Cat mask": 0.2,
    "Black beanie": 0.2,
    "Black baseball cap": 0.2,
    "Winona": 0.05,
    "Wavy pink": 0.2,
    "Space buns undercut": 0.2,
    "Short peach": 0.2,
    "Short curly": 0.2,
    "Shego": 0.1,
    "Shaved": 0.2,
    "Red streaks": 0.2,
    "Red half shaved": 0.2,
    "Red fauxhawk": 0.2,
    "Red braids": 0.2,
    "Purple pointed fringe": 0.2,
    "Purple half shaved": 0.2,
    "Pointed fringe": 0.2,
    "Pink short": 0.2,
    "Pink short fringe long": 0.2,
    "Pink pony": 0.2,
    "Pink pixie": 0.2,
    "Pink fringe": 0.2,
    "Pink curly": 0.2,
    "Peach fringe": 0.2,
    "Peach anime": 0.2,
    "Orange mullet": 0.2,
    "Nun habit": 0.1,
    "Multicolour": 0.05,
    "Moon": 0.01,
    "Misty": 0.01,
    "Lydia": 0.01,
    "Long purple": 0.2,
    "Long black": 0.2,
    "Long black wavy": 0.2,
    "Lilac half shaved": 0.2,
    "Lilac cat ears": 0.2,
    "Leia": 0.1,
    "Jane": 0.05,
    "Harley Quinn": 0.01,
    "Grey half shaved": 0.2,
    "Green Ramona": 0.2,
    "Green pigtails": 0.2,
    "Green mullet": 0.001,
    "Green Mohican": 0.2,
    "Green glam": 0.2,
    "Green fringe": 0.2,
    "Green Chelsea": 0.2,
    "Green braids": 0.2,
    "Green anime": 0.2,
    "Green + black pony": 0.2,
    "Ginger short fringe long": 0.2,
    "Femme fatale hat": 0.01,
    "Egirl": 0.1,
    "Deathlock": 0.2,
    "Choppy": 0.2,
    "Bulma": 0.05,
    "Brown pigtails": 0.2,
    "Brown party pony": 0.2,
    "Brown bun": 0.2,
    "Brown braids": 0.2,
    "Blue space buns": 0.2,
    "Blue Ramona": 0.05,
    "Blue punk": 0.2,
    "Blue pony": 0.2,
    "Blue long": 0.2,
    "Blue fringe": 0.2,
    "Blue fringe long": 0.2,
    "Blonde tucked": 0.2,
    "Blonde streaks": 0.2,
    "Egirl": 0.2,
    "Blonde streak pixie": 0.2,
    "Blonde straight": 0.2,
    "Blonde side part": 0.2,
    "Blonde short fringe long": 0.2,
    "Blonde pony": 0.2,
    "Blonde pompadour": 0.2,
    "Blonde mullet": 0.2,
    "Blonde long": 0.2,
    "Blonde half shaved": 0.2,
    "Blonde glam": 0.1,
    "Blonde crown horns": 0.05,
    "Black tucked": 0.2,
    "Black spikes": 0.2,
    "Black short waves": 0.2,
    "Black short fringe": 0.2,
    "Black short fringe long": 0.2,
    "Black shaved pigtails": 0.2,
    "Black scene queen": 0.2,
    "Black red two tone": 0.2,
    "Black punk": 0.2,
    "Black pony": 0.2,
    "Black pompadour": 0.2,
    "Black pixie": 0.2,
    "Black pigtails": 0.2,
    "Black mullet": 0.2,
    "Black Mohawk": 0.2,
    "Black messy pony": 0.2,
    "Black long": 0.2,
    "Black high pigtails": 0.2,
    "Black half shaved": 0.2,
    "Black glam": 0.2,
    "Black fauxhawk": 0.2,
    "Black Chelsea": 0.2,
    "Black beehive": 0.2,
    "Billie": 0.01,
    "Zero Two": 0.001
  },
  "Earring Upper": {
    "Earring": 0.05,
    "Stud": 0.05
  },
  "Earring Lower": {
    "White plug": 0.1,
    "Tunnel": 0.1,
    "Star plug": 0.1,
    "Pink plug": 0.1,
    "Gold heart plug": 0.001,
    "Earring": 0.1,
    "Stud": 0.1,
    "Black Plug": 0.1
  },
  "Orbital Piercing": {
    "Orbital": 0.05
  },
  "Industrial Piercing": {
    "Industrial": 0.05
  },
  "Helix Piercing": {
    "Helix": 0.05
  },
  "Tragus Piercing": {
    "Tragus": 0.05
  },
  "Snug Piercing": {
    "Snug": 0.05
  },
  "Neck Accessory": {
    "Yellow Spotty Choker": 0.1,
    "XXX Necklace": 0.1,
    "X Necklace": 0.1,
    "Bloody Vampire teeth necklace": 0.1,
    "Tooth necklace": 0.1,
    "Thin band": 0.1,
    "String bow": 0.1,
    "Solana chain": 0.1,
    "Skull necklace": 0.1,
    "Sailor Moon Choker": 0.1,
    "Ruby crystal necklace": 0.1,
    "Ruby choker": 0.1,
    "Red ribbon": 0.1,
    "Red heart choker": 0.1,
    "Red collar": 0.1,
    "Red candy laces": 0.1,
    "Razorblade necklace": 0.1,
    "Rainbow necklace": 0.1,
    "Pink spotty choker": 0.1,
    "Peridot crystal necklace": 0.1,
    "Pentagram choker": 0.1,
    "Pearl necklace": 0.1,
    "Patterned choker": 0.1,
    "Padlock": 0.1,
    "Moon necklace": 0.1,
    "Lace choker": 0.1,
    "Heart of the ocean": 0.01,
    "Heart chain studded": 0.1,
    "Handcuff choker": 0.1,
    "Gold skull necklace": 0.1,
    "Gold ring necklace": 0.1,
    "Gold leash": 0.1,
    "Gold heart locket": 0.1,
    "Gold choker": 0.1,
    "Gold choker 2": 0.1,
    "Gold chain": 0.001,
    "Eyeball necklace": 0.1,
    "Dollar chain": 0.1,
    "Daddy choker": 0.1,
    "Cry baby necklace": 0.1,
    "Coffin choker": 0.1,
    "Bone choker": 0.1,
    "Blue lacy bow": 0.1,
    "Blue heart collar": 0.1,
    "Bloody vampire teeth necklace": 0.1,
    "Bloody choker": 0.1,
    "Black thick choker": 0.1,
    "Black studded leather ring": 0.1,
    "Black studded heart collar": 0.1,
    "Black studded collar": 0.1,
    "Black studded choker": 0.1,
    "Black ruffle": 0.1,
    "Black ruffle + lace": 0.1,
    "Black ribbon": 0.1,
    "Black leather ring": 0.1,
    "Black leather heart": 0.1,
    "Black leash": 0.1,
    "Black lace": 0.1,
    "Black lace choker": 0.1,
    "Black heart collar": 0.1,
    "Black heart choker studded": 0.1,
    "Black harness": 0.1,
    "Black crescent moon": 0.1,
    "Black collar": 0.1,
    "Black cameo choker": 0.1,
    "Bat choker": 0.1,
    "Barb wire": 0.1,
    "Baby choker": 0.1,
    "Aquamarine crystal necklace": 0.1,
    "Anchor necklace": 0.1,
    "Anarchy necklace": 0.1,
    "Amethyst crystal necklace": 0.1,
    "Amber crystal necklace": 0.1,
    "13 necklace": 0.1
  },
  "Clothes": {
    "Yellow tshirt": 0.1,
    "White vest": 0.1,
    "White tshirt": 0.1,
    "White stripes": 0.1,
    "White polo": 0.1,
    "Track jacket": 0.1,
    "Shirt collar": 0.1,
    "Sailor shirt": 0.1,
    "Red stripes": 0.1,
    "Red bustier": 0.1,
    "Red + black segments": 0.1,
    "Purple stripes": 0.1,
    "Purple + Cream Segments": 0.1,
    "Pink vest": 0.1,
    "Pink tshirt": 0.1,
    "Pink sprinkles": 0.1,
    "Pink segments": 0.1,
    "Pink polo": 0.1,
    "Pink hoodie": 0.1,
    "Pink heart cutout": 0.1,
    "Pink braces": 0.1,
    "Pilgrim dress": 0.1,
    "Overalls": 0.1,
    "Lilac vest": 0.1,
    "Leopard spots": 0.1,
    "Houndstooth": 0.1,
    "Hoodie": 0.1,
    "Heart shirt": 0.1,
    "Grey tshirt": 0.1,
    "Grey polo": 0.1,
    "Flannel": 0.1,
    "Fishnets": 0.1,
    "Claret + Blue segments": 0.1,
    "Camo": 0.1,
    "Black vest": 0.1,
    "Black tshirt": 0.1,
    "Black strap vest": 0.1,
    "Black segments": 0.1,
    "Black heart cutout": 0.1,
    "Black dungarees": 0.1,
    "Black crossover harness": 0.1,
    "Black corset": 0.1,
    "Black bustier": 0.1,
    "Black braces": 0.1,
    "Black bandeau": 0.1,
    "Alice dress": 0.1,
    "666": 0.1
  },
  "Chest Accessory": {
    "Cleavage": 0.1,
    "Red straps": 0.1,
    "Purple straps": 0.1,
    "Pink straps": 0.1,
    "Pentagram harness": 0.05,
    "Black straps": 0.1
  },

  "Eye Accessory": {
    "Moon Tiara": 0.01,
    "Nurse eye patch": 0.01,
    "Hero mask": 0.05,
    "Black eye patch": 0.1
  },
  "Eyes": {
    "Starstruck": 0.01,
    "Starry": 0.001,
    "Sith": 0.01,
    "Rolling": 0.05,
    "Heart": 0.01,
    "Cross": 0.05,
    "Black": 0.01
  },

  "Eye Shadow": {
    "Red": 0.2,
    "Pink": 0.2,
    "Pale teal": 0.2,
    "Pale blue": 0.2,
    "Orange": 0.2,
    "Olive": 0.2,
    "Lilac": 0.2,
    "Light pink": 0.2,
    "Grey": 0.2,
    "Gold eyeshadow": 0.001,
    "Dark purple": 0.2,
    "Dark grey": 0.2,
    "Dark brown": 0.2,
    "Dark blue": 0.2,
    "Brown": 0.2,
    "Black": 0.2
  },
  "Eyebrows": {
    "Lost soul eyebrows": 0.01,
    "goth gfs eyebrows": 0.01,
    "uwu": 0.05,
    "thick": 0.05,
    "red": 0.2,
    "rainbow": 0.1,
    "pink": 0.2,
    "pencil": 0.05,
    "green": 0.2,
    "Gold brows": 0.001,
    "flapper": 0.05,
    "dark blonde": 0.2,
    "concerned": 0.05,
    "bushy": 0.1,
    "blue": 0.2,
    "blonde": 0.2,
    "black": 0.2,
    "angry": 0.05
  },
  "Nose Accessory": {
    "witch nose": 0.01,
    "white plaster": 0.01,
    "purple plaster": 0.01,
    "pink plaster": 0.01,
    "mouse whiskers": 0.01,
    "beige plaster": 0.01
  },
  "Under Eye Makeup": {
    "Red tears": 0.01,
    "Red smudged": 0.05,
    "Pink smudged": 0.05,
    "Harley Quinn": 0.05,
    "Gold tears": 0.001,
    "Blue tears": 0.01,
    "Black tears": 0.01,
    "Black smudged": 0.05
  },
  "Face Paint": {
    "Raccoon": 0.01,
    "Red Eye Paint": 0.01,
    "Thick black": 0.01,
    "White paint": 0.01,
    "War paint": 0.01,
    "Stars": 0.01,
    "Lines tattoo": 0.01,
    "Glasgow smile": 0.01,
    "Cartoon lashes": 0.01,
    "Blood splatter": 0.01
  },
  "Blush": {
    "Blush 1": 0.1,
    "Blush 2": 0.1,
    "Blush 3": 0.1,
    "Blush 4": 0.1,
    "Blush 5": 0.1 
  },
  "Eyes Base": {
    "Regular": 1
  },
  "Eyelashes & Liner": {
    "Wings x3": 0.1,
    "Wings x2": 0.1,
    "Thick top": 0.1,
    "Thick full": 0.1,
    "Small wings": 0.1,
    "Large wings": 0.1,
    "Full": 0.1,
    "Full lashes + wings": 0.1,
    "Full half": 0.1,
    "Bottom": 0.1
  },
  "Cheekbone": {
    "Three dots": 0.05,
    "Tear drop outline": 0.05,
    "Tear drop": 0.05,
    "Star": 0.05,
    "Spider web": 0.05,
    "Spider": 0.05,
    "Smile sad": 0.05,
    "Rose": 0.05,
    "PMA": 0.05,
    "Pentagram": 0.05,
    "NYHC": 0.05,
    "Inverted rose": 0.05,
    "Inverted cross": 0.05,
    "Heart": 0.05,
    "Dollar": 0.05,
    "Dagger": 0.05,
    "Crossbones": 0.05,
    "Cross": 0.05,
    "Cheekbone piercing": 0.05,
    "Broken heart": 0.05,
    "Barb wire": 0.05,
    "ACAB": 0.05,
    "Thirteen": 0.05
  },
  "Nose Piercing Right": {
    "Nose Ring Right": 0.1
  },
  "Nose Piercing Left": {
    "Nose Stud Left": 0.1,
    "Nose Ring Left": 0.1
  },
  "Septum Piercing": {
    "septum ring": 0.1,
    "septum bullring": 0.1
  },
  "Monroe Piercing": {
    "Monroe": 0.1
  },
  "Medusa Piercing": {
    "Medusa": 0.1
  },
  "Madonna Piercing": {
    "Madonna": 0.1
  },
  "Labret Right": {
    "Ring": 0.1,
    "Stud": 0.1
  },
  "Labret Left": {
    "Ring": 0.1,
    "Stud": 0.1
  },
  "Labret Centre": {
    "Ring": 0.1,
    "Stud": 0.1
  },
  "Lipstick": {
    "Violet": 0.2,
    "Vampire teeth": 0.01,
    "Teal": 0.2,
    "Red": 0.2,
    "Pink": 0.2,
    "Peach": 0.2,
    "Orange": 0.2,
    "Olive": 0.2,
    "Mauve": 0.2,
    "Light Red": 0.2,
    "Light purple": 0.2,
    "Light pink": 0.2,
    "Hot pink": 0.2,
    "Gold lipstick": 0.001,
    "Dark purple": 0.2,
    "Dark grey": 0.2,
    "Blue": 0.2,
    "Black": 0.2,
    "Black + White": 0.05,
    "Beige": 0.2,
    "Amidala": 0.01
  },
  "Bridge Piercing": {
    "Bridge": 0.05
  },
  "Beauty Mark": {
    "Beauty Mark 1": 0.05,
    "Beauty Mark 2": 0.05,
    "Beauty Mark 3": 0.05,
    "Beauty Mark 4": 0.05,
    "Beauty Mark 5": 0.05,
    "Beauty Mark 6": 0.05
  },
  "Forehead Tattoo": {
    "Gold pentagram": 0.001,
    "Forehead cross paint": 0.05,
    "Cross forehead": 0.05,
    "Barb wire": 0.01
  },
  "Scalp Tattoo": {
    "Spider web": 0.05,
    "Spider": 0.05,
    "Demon": 0.05
  },
  "Head Side Tattoo": {
    "Snake": 0.05,
    "Panther": 0.05,
    "Ouija": 0.05,
    "Lipstick": 0.05,
    "Heart padlock": 0.05,
    "Dragon": 0.05
  },
  "Shoulder Tattoo": {
    "Succulent": 0.05,
    "Snake": 0.05,
    "Skull": 0.05,
    "Reptile": 0.05,
    "Peach": 0.05,
    "Monkey": 0.05,
    "Medusa": 0.05,
    "Lantern": 0.05,
    "Imp": 0.05,
    "Ghost": 0.05,
    "Flowers": 0.05,
    "Devil": 0.05,
    "Coffin Skull": 0.05,
    "Coffin Eye": 0.05,
    "Candle": 0.05,
    "Cactus": 0.05,
    "Bat": 0.05,
    "Anchor": 0.05,
  },
  "Chest Tattoo": {
    "Web Diamond": 0.05,
    "Umbrella Rose": 0.05,
    "Tiger": 0.05,
    "Stars": 0.05,
    "Spiderweb": 0.05,
    "Spider": 0.05,
    "Ouija": 0.05,
    "Medusa": 0.05,
    "Illuminati": 0.05,
    "Hourglass": 0.05,
    "Flowers": 0.05,
    "Eye": 0.05,
    "Eagle": 0.05,
    "Dragon": 0.05,
    "Devil": 0.05,
    "Demon": 0.05,
    "Coffin skull": 0.05,
    "Hand": 0.05,
    "Butterfly": 0.05,
    "Anchor": 0.05,
  },
  "Base": {
    "Base": 1
  },
  "Skin Tone": {
    "Zombie green": 0.05,
    "Zombie decomposed": 0.05,
    "Vitiligo": 0.1,
    "Space": 0.01,
    "Sally": 0.05,
    "Red": 0.05,
    "Medium 4": 0.2,
    "Medium 3": 0.2,
    "Medium 2": 0.2,
    "Medium 1": 0.2,
    "Light freckles": 0.1,
    "Light 1": 0.2,
    "Light 2": 0.2,
    "Light 3": 0.2,
    "Light 4": 0.2,
    "Grey Alien": 0.01,
    "Green": 0.01,
    "Gold": 0.001,
    "Deep 1": 0.2,
    "Deep 2": 0.2,
    "Deep 3": 0.2,
    "Deep 4": 0.2,
    "Corpse paint": 0.1,
    "CMN": 0.1,
    "Blue glow": 0.001
  },
  "Background": {
    "Beige": 0.2,
    "Black": 0.2,
    "Galactic": 0.001,
    "Green": 0.2,
    "Orange": 0.2,
    "Pink": 0.2,
    "Purple": 0.2,
    "Red": 0.2,
    "Teal": 0.2,
    "Yellow": 0.2
  }
}